services:
  - name: my-backend
    type: web
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
  - name: my-frontend
    type: static
    plan: free
    buildCommand: npm run build
    startCommand: npm start
