services:
  - name: my-backend
    type: web
    region: sg  # Use Singapore region code
    plan: free
    buildCommand: npm install
    startCommand: npm start
  - name: my-frontend
    type: web
    region: sg  # Use Singapore region code for frontend
    plan: free
    buildCommand: npm run build
    startCommand: npm start
