services:
  - name: frontend
    type: web
    plan: free
    runtime: node
    buildCommand: npm run build
    startCommand: serve -s build  # Use this if you're serving a static React build
    region: us-west-2  # Valid region for Render
  
  - name: backend
    type: web
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    region: us-west-2  # Valid region for Render
