services:
  # Backend Service
  - type: web
    name: backend-service
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    region: us
    branch: full_stack

  # Frontend Service
  - type: web
    name: frontend-service
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    plan: free
    region: us
    branch: full_stack
